<!-- external references that can be used in any doc -->
[cjson]:          http://www.kyne.com.au/~mark/software/lua-cjson-manual.html#_api_functions
[lfs]:            http://keplerproject.github.com/luafilesystem/manual.html#reference
[libvlc]:         http://www.videolan.org/developers/vlc/doc/doxygen/html/modules.html
[lpeg.re]:        http://www.inf.puc-rio.br/~roberto/lpeg/re.html
[lpeg]:           http://www.inf.puc-rio.br/~roberto/lpeg/
[luasocket]:      http://w3.impa.br/~diego/software/luasocket/reference.html
[struct]:         http://www.inf.puc-rio.br/~roberto/struct/
